### ISSUE TITLE
Code Review - Morning Session 5/8

### ISSUE THREAD

**Issue by alonsofalconi** [StarSheriff2/Javascript-API-Page#30]
### Recommendation
- Please, instead of using a hard-coded iterations limit, I would recommend using the array length.
https://github.com/StarSheriff2/Javascript-API-Page/blob/6c09a3b5265f8827e17c1f498287a8f82591a0b4/src/app/DOM/objects_renderer.js#L13

**Comment by StarSheriff2** [comment]
yes, we will change this.
